package br.com.vainaweb.escolat3.enums;

public enum Curso {

    BACHARELADO_CIENCIA_DA_COMPUTACAO,
    BACHARELADO_SISTEMAS_DE_INFORMACAO,
    TECNOLOGO_ANALISE_DESENVOLVIMENTO_SISTEMAS,
    BACHARELADO_ENGENHARIA_SOFTWARE
}
